build :
	@bundle exec jekyll build

serve :
	@bundle exec jekyll serve --incremental --config _config.yml,_config-local.yml

clean :
	@rm --force --recursive _site .sass-cache .jekyll-cache .jekyll-metadata
